CREATE TABLE IF NOT EXISTS admins (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(80) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  must_change_password TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS services (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(160) NOT NULL UNIQUE,
  label VARCHAR(180) NOT NULL,
  label_fr VARCHAR(180) NULL,
  label_es VARCHAR(180) NULL,
  title VARCHAR(180) NOT NULL,
  title_fr VARCHAR(180) NULL,
  title_es VARCHAR(180) NULL,
  blurb TEXT NOT NULL,
  blurb_fr TEXT NULL,
  blurb_es TEXT NULL,
  items_json LONGTEXT NOT NULL,
  items_json_fr LONGTEXT NULL,
  items_json_es LONGTEXT NULL,
  challenge TEXT NOT NULL,
  challenge_fr TEXT NULL,
  challenge_es TEXT NULL,
  response TEXT NOT NULL,
  response_fr TEXT NULL,
  response_es TEXT NULL,
  outcome TEXT NOT NULL,
  outcome_fr TEXT NULL,
  outcome_es TEXT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX services_active_sort (is_active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sectors (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(180) NOT NULL UNIQUE,
  name VARCHAR(180) NOT NULL,
  name_fr VARCHAR(180) NULL,
  name_es VARCHAR(180) NULL,
  description TEXT NOT NULL,
  description_fr TEXT NULL,
  description_es TEXT NULL,
  body MEDIUMTEXT NULL,
  body_fr MEDIUMTEXT NULL,
  body_es MEDIUMTEXT NULL,
  image_path VARCHAR(500) NULL,
  icon VARCHAR(80) NOT NULL DEFAULT 'default',
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX sectors_active_sort (is_active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS service_sectors (
  service_id INT UNSIGNED NOT NULL,
  sector_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (service_id, sector_id),
  CONSTRAINT fk_service_sector_service FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE CASCADE,
  CONSTRAINT fk_service_sector_sector FOREIGN KEY (sector_id) REFERENCES sectors(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mandates (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  service_id INT UNSIGNED NOT NULL,
  custom_label VARCHAR(180) NOT NULL,
  custom_label_fr VARCHAR(180) NULL,
  custom_label_es VARCHAR(180) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_mandate_service FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE CASCADE,
  INDEX mandates_active_sort (is_active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS videos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(220) NOT NULL,
  title_fr VARCHAR(220) NULL,
  title_es VARCHAR(220) NULL,
  description TEXT NULL,
  description_fr TEXT NULL,
  description_es TEXT NULL,
  video_url VARCHAR(700) NULL,
  thumbnail_path VARCHAR(500) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX videos_active_sort (is_active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS projects (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(180) NOT NULL UNIQUE,
  title VARCHAR(240) NOT NULL,
  title_fr VARCHAR(240) NULL,
  title_es VARCHAR(240) NULL,
  infrastructure_class VARCHAR(160) NOT NULL,
  infrastructure_class_fr VARCHAR(160) NULL,
  infrastructure_class_es VARCHAR(160) NULL,
  scale VARCHAR(120) NULL,
  scale_fr VARCHAR(120) NULL,
  scale_es VARCHAR(120) NULL,
  location VARCHAR(180) NULL,
  location_fr VARCHAR(180) NULL,
  location_es VARCHAR(180) NULL,
  sector_name VARCHAR(180) NULL,
  sector_name_fr VARCHAR(180) NULL,
  sector_name_es VARCHAR(180) NULL,
  client VARCHAR(240) NULL,
  client_fr VARCHAR(240) NULL,
  client_es VARCHAR(240) NULL,
  summary TEXT NULL,
  summary_fr TEXT NULL,
  summary_es TEXT NULL,
  body MEDIUMTEXT NULL,
  body_fr MEDIUMTEXT NULL,
  body_es MEDIUMTEXT NULL,
  image_path VARCHAR(500) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  status ENUM('draft', 'published') NOT NULL DEFAULT 'published',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX projects_status_sort (status, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS insights (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(180) NOT NULL UNIQUE,
  title VARCHAR(240) NOT NULL,
  title_fr VARCHAR(240) NULL,
  title_es VARCHAR(240) NULL,
  category VARCHAR(100) NOT NULL,
  category_fr VARCHAR(100) NULL,
  category_es VARCHAR(100) NULL,
  excerpt TEXT NOT NULL,
  excerpt_fr TEXT NULL,
  excerpt_es TEXT NULL,
  body MEDIUMTEXT NULL,
  body_fr MEDIUMTEXT NULL,
  body_es MEDIUMTEXT NULL,
  image_path VARCHAR(500) NULL,
  link_label VARCHAR(80) NOT NULL DEFAULT 'Read more',
  link_label_fr VARCHAR(80) NULL,
  link_label_es VARCHAR(80) NULL,
  published_at DATETIME NOT NULL,
  status ENUM('draft', 'published') NOT NULL DEFAULT 'published',
  featured TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX insights_status_date (status, published_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS site_settings (
  setting_key VARCHAR(120) PRIMARY KEY,
  setting_value MEDIUMTEXT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS staff (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(180) NOT NULL UNIQUE,
  name VARCHAR(180) NOT NULL,
  role VARCHAR(180) NOT NULL,
  role_fr VARCHAR(180) NULL,
  role_es VARCHAR(180) NULL,
  image_path VARCHAR(500) NULL,
  short_bio TEXT NULL,
  short_bio_fr TEXT NULL,
  short_bio_es TEXT NULL,
  bio MEDIUMTEXT NULL,
  bio_fr MEDIUMTEXT NULL,
  bio_es MEDIUMTEXT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX staff_active_sort (is_active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS newsroom (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(180) NOT NULL UNIQUE,
  title VARCHAR(240) NOT NULL,
  title_fr VARCHAR(240) NULL,
  title_es VARCHAR(240) NULL,
  category VARCHAR(60) NOT NULL DEFAULT 'press',
  excerpt TEXT NOT NULL,
  excerpt_fr TEXT NULL,
  excerpt_es TEXT NULL,
  body MEDIUMTEXT NULL,
  body_fr MEDIUMTEXT NULL,
  body_es MEDIUMTEXT NULL,
  image_path VARCHAR(500) NULL,
  location VARCHAR(180) NULL,
  location_fr VARCHAR(180) NULL,
  location_es VARCHAR(180) NULL,
  closing_date DATE NULL,
  external_url VARCHAR(700) NULL,
  published_at DATETIME NOT NULL,
  status ENUM('draft', 'published') NOT NULL DEFAULT 'published',
  featured TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX newsroom_status_date (status, published_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS offices (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(180) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX offices_active_sort (is_active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inquiries (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  category VARCHAR(40) NOT NULL DEFAULT 'general',
  name VARCHAR(180) NOT NULL,
  company VARCHAR(180) NULL,
  email VARCHAR(254) NOT NULL,
  phone VARCHAR(60) NULL,
  message TEXT NOT NULL,
  status ENUM('new', 'read', 'archived') NOT NULL DEFAULT 'new',
  email_sent TINYINT(1) NOT NULL DEFAULT 0,
  email_error TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX inquiries_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS testimonials (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  quote TEXT NOT NULL,
  quote_fr TEXT NULL,
  quote_es TEXT NULL,
  author_name VARCHAR(180) NOT NULL,
  author_title VARCHAR(180) NULL,
  author_title_fr VARCHAR(180) NULL,
  author_title_es VARCHAR(180) NULL,
  company VARCHAR(180) NULL,
  logo_path VARCHAR(500) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX testimonials_active_sort (is_active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS media (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  size INT UNSIGNED NOT NULL,
  width INT UNSIGNED NULL,
  height INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX media_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(254) NOT NULL UNIQUE,
  subscribed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_active TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
