<?php
declare(strict_types=1);

return [
    'settings' => [
        'services_title' => 'Our Services',
        'services_intro' => 'Comprehensive infrastructure advisory across the full project lifecycle',
        'sectors_title' => 'Sectors We Serve',
        'sectors_intro' => "Global sector expertise, applied to Africa's infrastructure priorities",
        'videos_title' => 'Infrastructure in Action',
        'experience_title' => 'Experience Across Africa',
        'experience_intro' => 'Selected mandates, ordered by infrastructure class.',
        'insights_title' => 'Insights & Thought Leadership',
        'insights_intro' => "Navigating Africa's infrastructure opportunities",
        'metric_1_value' => '150', 'metric_1_suffix' => '+', 'metric_1_label' => 'Infrastructure Projects Advised',
        'metric_2_value' => '45', 'metric_2_suffix' => '+', 'metric_2_label' => 'Billion USD Mobilised',
        'metric_3_value' => '18', 'metric_3_suffix' => '+', 'metric_3_label' => 'African Countries',
        'lifecycle_title' => 'The infrastructure lifecycle.',
        'lifecycle_intro' => 'We carry a project from first screening through to operations — the same team, the same evidence base, no handover gaps.',
        'delivery_title' => 'How We Deliver',
        'delivery_intro' => 'Integrated teams that combine sector expertise, financial structuring and risk management',
        'contact_email' => 'info@acmirs.com',
        'contact_phone' => '+1 (234) 567-890',
        'cta_title' => "Ready to unlock Africa's infrastructure potential?",
        'cta_body' => "Let's explore how ACMIRS can support your next critical infrastructure initiative.",
    ],
    'sectors' => [
        ['Energy & Power', 'Thermal, renewable, transmission and distribution infrastructure', 'energy'],
        ['Transport & Logistics', 'Road, rail, port and aviation infrastructure', 'transport'],
        ['Water & Sanitation', 'Water supply, wastewater and drainage infrastructure', 'water'],
        ['Oil & Gas', 'Upstream, midstream and downstream energy infrastructure', 'oil-gas'],
        ['Ports, Marine & Blue Economy', 'Port development, maritime and blue economy initiatives', 'marine'],
        ['Urban Development', 'Cities, housing and municipal infrastructure', 'urban'],
        ['Digital Infrastructure', 'Telecom, broadband, data centres and digital connectivity', 'digital'],
        ['Industrial & Manufacturing', 'Special economic zones, industrial parks and manufacturing facilities', 'industry'],
        ['Agriculture & Agro-processing', 'Irrigation, storage, processing and value-chain infrastructure', 'agriculture'],
    ],
    'services' => [
        [
            'preparation', 'Project Preparation', 'Rigorous analysis and stakeholder alignment to build investable, bankable and sustainable infrastructure solutions.',
            ['Market & Sector Analysis', 'Stakeholder & Institutional Alignment', 'Project Identification & Screening', 'Financial Modelling & Viability', 'Environmental & Social Scoping', 'Technical Due Diligence'],
            'Unclear needs, a weak pipeline and limited bankability constrain investment and delivery.',
            'We provide clarity, structure and bankable solutions that de-risk projects and attract credible capital.',
            'Investable projects, aligned stakeholders and stronger pathways to financial close and impact.',
            ['Transport & Logistics', 'Energy & Power', 'Water & Sanitation', 'Urban Development', 'Ports, Marine & Blue Economy'],
        ],
        [
            'ppp', 'PPP Structuring', 'Commercially robust PPP structures, risk allocation and contractual frameworks that stand up to lender and government scrutiny.',
            ['Delivery Option & VfM Analysis', 'Risk Allocation Frameworks', 'Concession & Contract Structuring', 'Government Support Instruments', 'Affordability & Fiscal Analysis', 'Negotiation Support to Close'],
            'Unbalanced risk transfer and untested structures stall PPPs before the market is engaged.',
            'We design structures, contracts and support packages that are bankable and politically durable.',
            'A market-tested PPP structure, credible bidders and defensible value for money.',
            ['Transport & Logistics', 'Water & Sanitation', 'Energy & Power'],
        ],
        [
            'capital', 'Capital Raising', 'Financial structuring and capital mobilisation across DFI, commercial, blended and local currency sources.',
            ['Financial Modelling & Sensitivities', 'Funding Strategy & Capital Structure', 'DFI & Lender Engagement', 'Blended & Concessional Finance', 'Credit Enhancement & Guarantees', 'Financial Close Management'],
            'Projects are technically sound but cannot secure the right cost and tenor of capital.',
            'We build the financial case, structure the capital stack and manage lender processes end to end.',
            'Committed funding on terms that hold up through construction and operations.',
            ['Energy & Power', 'Transport & Logistics', 'Industrial & Manufacturing', 'Digital Infrastructure'],
        ],
        [
            'transaction', 'Transaction Advisory', 'Disciplined procurement and transaction management from market sounding through award and contract signature.',
            ['Procurement Strategy & Planning', 'Market Sounding & Investor Outreach', 'Bid Documentation & Evaluation', 'Legal & Regulatory Assessment', 'Negotiation Strategy', 'Award & Contract Management'],
            'Weak process design invites challenge, delay and poor-quality bids.',
            'We run transparent, competitive processes with documentation that withstands review.',
            'Credible competition, defensible awards and faster time to contract.',
            ['Transport & Logistics', 'Water & Sanitation', 'Urban Development'],
        ],
        [
            'procurement', 'Tender & Procurement Support', 'Advisory support on both sides of the table — helping global bidders compete credibly, and helping governments and DFIs run procurement processes that hold up to scrutiny.',
            ['Bid & Proposal Strategy for Global Entities', 'Tender Documentation & Compliance Review', 'Government & DFI Procurement Design', 'Evaluation Criteria & Scoring Frameworks', 'Pre-Qualification & Vendor Due Diligence', 'Procurement Dispute & Appeals Support'],
            'Complex tender rules and unclear evaluation criteria slow bidders down and expose procuring authorities to challenge.',
            'We advise bidding entities on compliant, competitive proposals, and help governments and DFIs design procurement that is transparent and defensible.',
            'Stronger bids, cleaner procurement processes and faster, more defensible contract awards.',
            ['Transport & Logistics', 'Energy & Power', 'Oil & Gas', 'Ports, Marine & Blue Economy'],
        ],
        [
            'implementation', 'Implementation Support', 'Institutional and delivery support that converts signed agreements into assets and services on the ground.',
            ['Implementation Planning Frameworks', 'PMO Setup & Capacity Building', 'Contract & Performance Monitoring', 'Construction Oversight Support', 'Handover & Operations Readiness', 'Monitoring, Evaluation & Learning'],
            'Delivery capacity gaps erode value long after the transaction is closed.',
            'We embed governance, monitoring and capability so obligations are actually met.',
            'Projects delivered on time, on scope and measurably in the public interest.',
            ['Transport & Logistics', 'Agriculture & Agro-processing', 'Urban Development'],
        ],
        [
            'esg', 'ESG & Sustainability', 'Environmental, social and climate assessment aligned to IFC Performance Standards and national requirements.',
            ['ESIA & Social Impact Assessment', 'Climate Resilience Screening', 'Resettlement & Livelihood Planning', 'Gender & Inclusion Assessment', 'Safeguard Compliance Monitoring', 'Sustainability Reporting'],
            'Safeguard gaps delay approvals and expose projects to reputational and lender risk.',
            'We assess, mitigate and monitor impacts to standards lenders and regulators accept.',
            'Compliant, resilient projects with community support and durable social licence.',
            ['Energy & Power', 'Water & Sanitation', 'Agriculture & Agro-processing', 'Industrial & Manufacturing'],
        ],
    ],
    'videos' => [
        ['Power Transmission & Generation', 'Energy infrastructure delivery across the continent.'],
        ['Digital Infrastructure', 'Connectivity and digital infrastructure in action.'],
        ['Water Infrastructure', 'Water and sanitation systems improving communities.'],
    ],
    'projects' => [
        ['ppp-geothermal-kenya', 'PPP Geothermal', 'Economic infrastructure', '140 MW', 'Kenya', 'Energy & Power', '', 10],
        ['oil-refinery-uganda', 'Oil Refinery', 'Economic infrastructure', '60,000 BOPD', 'Uganda', 'Oil & Gas', '', 20],
        ['geothermal-power-development', 'Geothermal Power Development', 'Economic infrastructure', '20 MW', '', 'Energy & Power', '', 30],
        ['africa-power-interconnection', 'Africa Power Interconnection Transaction Advisory', 'Economic infrastructure', '', 'Continental', 'Energy & Power', 'AfDB', 40],
        ['railways-diagnostic-study', 'Railways Diagnostic Study', 'Economic infrastructure', '', 'Continental', 'Transport', 'World Bank / Infrastructure Consortium for Africa', 50],
        ['digital-connectivity-acceleration', 'Digital Connectivity Acceleration', 'Economic infrastructure', '', 'Kenya', 'Digital Infrastructure', 'Korea / World Bank', 60],
        ['scr-procurement-support', 'SCR Procurement Support', 'Economic infrastructure', '', 'Uganda', 'Transport', '', 70],
        ['copper-kilembe-mines', 'Copper–Kilembe Mines', 'Economic infrastructure', '', 'Uganda', 'Extractives', '', 80],
        ['national-irrigation-master-plan', 'National Irrigation Master Plan', 'Quasi-economic infrastructure', '', 'Uganda', 'Water & Agriculture', '', 90],
    ],
    'insights' => [
        ['accelerating-infrastructure-finance-in-africa', 'Accelerating Infrastructure Finance in Africa', 'Research', 'How blended finance and DFI capital are unlocking private investment in critical infrastructure', 'Read more'],
        ['future-of-ppps-in-africa', 'The Future of PPPs in Africa', 'Podcast', "Lessons from recent transactions and what's needed for the next generation of deals", 'Listen'],
        ['digital-connectivity-as-infrastructure', 'Digital Connectivity as Infrastructure', 'Article', "Why broadband and data centers are as critical as roads and power to Africa's development", 'Read more'],
    ],
];

